### ISSUE TITLE
Having two roles has the bot automatically opt for the longer one in function roleRequest

### ISSUE THREAD

**Issue by eyang1608** [ADawesomeguy/AwesomeMod#3]
![image](https://user-images.githubusercontent.com/64386991/114803665-df670980-9d6d-11eb-9332-7555dd5920f0.png)

As shown here: in this scenario, there are two roles, @testing and @test. The bot will automatically select @testing instead of @test, even though @test has a complete match of the string.

**Comment by eyang1608** [comment]
I would assume a relatively easy way to fix this issue is to have matched case roles take priority. This can be done with if-statements, however the code isn't as straightforward and I will need to investigate a little more.

**Comment by eyang1608** [comment]
After further inspection, this bug also happens to the kick and ban commands, but instead of roles it occurs with usernames.

**Comment by abheekda1** [comment]
Just to let you know - it's not the longer one, it's the one higher in the hierarchy. This is gonna take some coding to fix (gonna have to have the user decide if there's more than one result). I'll do my best to fix it as soon as I can.

**Comment by abheekda1** [comment]
I've decided to make it so that it opts for the shorter one instead of giving the user multiple options, which I've already implemented in `$usersWith`. Much easier to do, and it basically picks the most specific option.

**Comment by eyang1608** [comment]
That works! The `$usersWith` command does not have the issue mentioned in the opening post anymore.
